export const EventData = [
  {
    id: "1",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "2",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "3",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "4",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "5",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "6",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",

    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "7",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "8",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "9",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "10",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "11",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "12",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "13",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "14",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "15",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "16",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "17",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "18",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "19",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "20",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "21",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "22",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "23",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "24",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "25",
    title: "EventTitle1",
    date: "EventDate",
    city: "EventCity1",
    img: "event1.png",
    price: 20000,
    date2: "26/08/2024",
    startTime: 10.0,
    topics: 12,
    quizzes: 145,
    certifications: "yes",
    totalSeat: 300,
    score: 4.8,
    students: 2500,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
  {
    id: "26",
    title: "EventTitle2",
    date: "EventDate",
    city: "EventCity2",
    img: "event2.png",
    price: 35000,
    date2: "22/06/2024",
    startTime: 10.3,
    topics: 15,
    quizzes: 185,
    certifications: "no",
    totalSeat: 150,
    score: 3.8,
    students: 2000,
    createBy: "David Millar",
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
  },
];
