import blog1 from "../../../assets/images/blogs/blog1.png";
export const Blogs_data = [
  {
    id: 1,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "علوم پایه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهی این خبر برای این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 2,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "توسعه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 3,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "علوم پایه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 4,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "علوم پایه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 5,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "علوم پایه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 6,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "سبک زندگی",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 7,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "سبک زندگی",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 8,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "توسعه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 9,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "توسعه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 10,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "علوم پایه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 11,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "علوم پایه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 12,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "توسعه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 13,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "سبک زندگی",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 14,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "سبک زندگی",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 15,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "توسعه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
  {
    id: 16,
    title: "توسعه خود را بسازید ",
    img: blog1,
    category: "علوم پایه",
    date: "2024/8/2",
    view: 20,
    like: 158,
    disLike: 58,
    studyTime: 5,
    commentsNumber: 3,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    bio: "این خبر برای این است که توسعه خود را بسازید و عنوان محتوای خود میتوانیذ قرار دهید این خبر برای",
  },
];
