import course1 from "../../../assets/images/courses/course1.png";
import course2 from "../../../assets/images/courses/course2.png";
import course3 from "../../../assets/images/courses/course3.png";

export const CoursesDataFa = [
  {
    id: "1",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است  که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "2",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "3",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "4",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "5",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "6",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "7",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "8",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "9",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "10",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "11",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "12",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "13",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "14",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "15",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "16",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "17",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "18",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "19",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "20",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "21",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "22",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "23",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "24",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "25",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "26",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "27",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "28",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "29",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "30",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "31",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "32",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "33",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "34",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "35",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "36",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "37",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "38",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "39",
    title: "آموزش جاوااسکریپت با خیال پردازی",
    img: course1,
    price: 20000,
    date: "26/08/2024",
    instructor: "محسن اسفندیاری",
    score: 4.8,
    category: ["توسعه", "سبک زندگی"],
    languages: "فارسی",
    level: "متوسط",
    duration: "11h 20m",
    lessons: 12,
    quizzes: 145,
    certifications: "yes",
    graduation: 25,
    students: 2500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "40",
    title: "طراحی کامل گرافیک برای مبتدی ها",
    img: course2,
    price: 134000,
    date: "26/03/2024",
    instructor: "مهدی اصغری",
    score: 3.2,
    category: ["طراحی", "علم داده", "توسعه", "سلامت"],
    languages: "انگلیسی",
    level: "مبتدی",
    duration: "11h 20m",
    lessons: 8,
    quizzes: 96,
    certifications: "no",
    graduation: 22,
    students: 3500,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
  {
    id: "41",
    title: "یادگیری دیجیتال مارکتینگ در فیس بوک",
    img: course3,
    price: 5200,
    date: "15/012/2024",
    instructor: "محمدرضا ساداتی",
    score: 4.9,
    category: ["بازاریابی", "سبک زندگی"],
    languages: "اسپانیایی",
    level: "پیشرفته",
    duration: "18h 20m",
    lessons: "15",
    quizzes: 155,
    certifications: "yes",
    graduation: 18,
    students: 2900,
    MajorElements: [
      "EventElement1",
      "EventElement2",
      "EventElement3",
      "EventElement4",
    ],
    overView: "test",
    training: "test",
    like: 165,
    disLike: 110,
    bio: "این دوره برای افراد مبتدی و تازه کار است که در آن مباحث پایه ای طراحی گرافیک و ",
  },
];
